version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_USER: notesuser
      DB_PASSWORD: notespassword
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: notesdb
      PORT: 8000
    depends_on:
      - db
    volumes:
      - .:/app  # optional: mount code for live reload in dev

volumes:
  mysql_data:
